name: Nuge CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  NODE_VERSION: '20'
  REGISTRY_URL: ghcr.io

jobs:
  # ==============================================
  # BACKEND TESTS AND LINTING
  # ==============================================
  backend-test:
    name: Backend Tests & Linting
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgis/postgis:15-3.3
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: nuge_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint backend code
        run: npm run lint:backend

      - name: Run backend type checking
        run: npm run type-check:backend

      - name: Run backend unit tests
        run: npm run test:backend -- --coverage
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/nuge_test
          REDIS_URL: redis://localhost:6379

      - name: Run backend E2E tests
        run: cd backend && npm run test:e2e
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/nuge_test
          REDIS_URL: redis://localhost:6379

      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          file: ./backend/coverage/lcov.info
          flags: backend

  # ==============================================
  # MOBILE TESTS AND LINTING
  # ==============================================
  mobile-test:
    name: Mobile Tests & Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint mobile code
        run: npm run lint:mobile

      - name: Run mobile type checking
        run: npm run type-check:mobile

      - name: Run mobile tests
        run: npm run test:mobile -- --coverage --watchAll=false

      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          file: ./mobile/coverage/lcov.info
          flags: mobile

  # ==============================================
  # BACKEND DEPLOYMENT TO RAILWAY
  # ==============================================
  deploy-backend:
    name: Deploy Backend to Railway
    runs-on: ubuntu-latest
    needs: [backend-test]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push' && vars.ENABLE_DEPLOYMENT == 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy to Railway
        run: cd backend && railway up --service backend
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Run database migrations
        run: cd backend && railway run npm run migrate:prod
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

  # ==============================================
  # MOBILE BUILD AND DEPLOY
  # ==============================================
  build-mobile:
    name: Build Mobile App
    runs-on: ubuntu-latest
    needs: [mobile-test]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push' && vars.ENABLE_DEPLOYMENT == 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Setup Expo CLI
        run: npm install -g @expo/cli eas-cli

      - name: Build for iOS (Preview)
        run: cd mobile && eas build --platform ios --profile preview --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Build for Android (Preview)
        run: cd mobile && eas build --platform android --profile preview --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

  # ==============================================
  # PRODUCTION MOBILE DEPLOYMENT
  # ==============================================
  deploy-mobile-production:
    name: Deploy Mobile to Production
    runs-on: ubuntu-latest
    needs: [build-mobile]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push' && vars.ENABLE_DEPLOYMENT == 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Setup Expo CLI
        run: npm install -g @expo/cli eas-cli

      - name: Publish OTA Update
        run: cd mobile && eas update --branch production --message "Production deployment from CI/CD"
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

  # ==============================================
  # SECURITY SCANNING
  # ==============================================
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Install dependencies
        run: npm ci

      - name: Backend dependency check
        run: npm audit --audit-level=high

      - name: Mobile dependency check
        run: npm audit --audit-level=high
